--

DROP TABLE IF EXISTS books;

DROP TABLE IF EXISTS subjects;

DROP TABLE IF EXISTS authors;

--

CREATE TABLE authors (
  id SERIAL PRIMARY KEY,

  first_name VARCHAR(80) NOT NULL,
  last_name VARCHAR(80) NOT NULL,

  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE authors ADD CONSTRAINT unique_author_name UNIQUE (first_name, last_name);

CREATE TABLE subjects (
  id SERIAL PRIMARY KEY,
	name  VARCHAR(80) NOT NULL,
  location VARCHAR(80),

  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE subjects ADD UNIQUE (name);

CREATE TABLE books (
  id SERIAL PRIMARY KEY,
  title VARCHAR(80) NOT NULL,
  author_id BIGINT NOT NULL REFERENCES authors (id),
  subject_id BIGINT NOT NULL REFERENCES subjects (id),

  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE books ADD CONSTRAINT unique_book_title_author UNIQUE (title, author_id);
