dist: bionic

sudo: required

notifications:
  email: false

language: go

go:
  - "1.12"
  - "1.13"

services:
  - docker

env:
  global:
  - GOARCH=amd64
  - TEST_HOST=127.0.0.1

before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - sleep 10

script:
  - export UPPERIO_DB_DEBUG=1
  - export GO111MODULE=on
  - make -C internal/tests server-up test server-down
